# Generated by Django 4.0.3 on 2022-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0003_estudiante_delete_datos_delete_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=200)),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
    ]
